
name: Build Master

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build the library
        run: ./gradlew library:assemble
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run unit tests
        run: ./gradlew library:test
      - name: Upload Reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-reports
          path: library/build/reports/tests
        if: always()
  code-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run detekt
        run: ./gradlew library:detekt
      - name: Upload Reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: detekt-reports
          path: library/build/reports/detekt/detekt.html
        if: always()
  release:
    runs-on: ubuntu-latest
    needs: [build, test, code-analysis]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build the library
        run: ./gradlew library:assemble
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "The changelog notes goes here"
          draft: true
          files: |
            library/build/outputs/aar/library-debug.arr
            library/build/outputs/aar/library-release.arr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


