
name: Build Master

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build the library
        run: ./gradlew library:assemble
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: library/build/outputs/aar
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run unit tests
        run: ./gradlew library:test
      - name: Upload Reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-reports
          path: library/build/reports/tests
        if: always()
  code-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run detekt
        run: ./gradlew library:detekt
      - name: Upload Reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: detekt-reports
          path: library/build/reports/detekt/detekt.html
        if: always()
  release:
    runs-on: ubuntu-latest
    needs: [ build, test, code-analysis ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.5
      - name: Download the build
        uses: actions/download-artifact@v2.0.10
        with:
          name: build
          path: downloaded-build
      - name: Extract version
        id: version
        run: |
          versionName=`cat library/build.gradle | grep 'versionName' | sed 's/[^0-9.]*//g'`
          echo "::set-output name=name::$versionName"
      - name: Create and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          CUSTOM_TAG: ${{ steps.version.outputs.name }}
      - name: Display structure of downloaded files
        run: |
          echo "steps.version.outputs.name: ${{ steps.version.outputs.name }}"
          echo "github.ref: ${{ github.ref }}"
          ls -R downloaded-build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "The changelog notes goes here"
          draft: true
          files: |
            downloaded-build/library-debug.aar
            downloaded-build/library-release.aar
